<?php

use App\Http\Controllers\Api\TrainingAdjustmentsController;
use App\Http\Controllers\Api\TrainingFeedbackV2Controller;
use App\Http\Controllers\Api\AiInsightsController;
use App\Http\Controllers\Api\AiPlanController;
use App\Http\Controllers\Api\AuthController;
use App\Http\Controllers\Api\ProfileController;
use App\Http\Controllers\Api\IntegrationsController;
use App\Http\Controllers\Api\TrainingContextController;
use App\Http\Controllers\Api\TrainingFeedbackController;
use App\Http\Controllers\Api\TrainingSignalsController;
use App\Http\Controllers\Api\WeeklyPlanController;
use App\Http\Controllers\Api\WorkoutsController;
use App\Http\Controllers\HealthController;
use App\Http\Controllers\MeController;
use Illuminate\Support\Facades\Route;

Route::get('/health', [HealthController::class, 'index']);
Route::get('/', fn () => response()->json(['status' => 'ok', 'service' => 'MarcinCoach API']));
Route::post('/auth/register', [AuthController::class, 'register']);
Route::post('/auth/login', [AuthController::class, 'login']);
Route::post('/integrations/strava/connect', [IntegrationsController::class, 'stravaConnect']);
Route::get('/integrations/strava/callback', [IntegrationsController::class, 'stravaCallback']);
Route::post('/integrations/strava/sync', [IntegrationsController::class, 'stravaSync']);
Route::post('/integrations/garmin/connect', [IntegrationsController::class, 'garminConnect']);
Route::post('/integrations/garmin/sync', [IntegrationsController::class, 'garminSync']);
Route::get('/integrations/garmin/status', [IntegrationsController::class, 'garminStatus']);
Route::get('/me', [MeController::class, 'index']);
Route::get('/me/profile', [ProfileController::class, 'show']);
Route::put('/me/profile', [ProfileController::class, 'update']);
Route::get('/training-feedback', [TrainingFeedbackController::class, 'index']);
Route::get('/training-signals', [TrainingSignalsController::class, 'index']);
Route::get('/training-context', [TrainingContextController::class, 'index']);
Route::get('/training-adjustments', [TrainingAdjustmentsController::class, 'index']);
Route::get('/weekly-plan', [WeeklyPlanController::class, 'index']);
Route::get('/ai/insights', [AiInsightsController::class, 'index']);
Route::get('/ai/plan', [AiPlanController::class, 'show']);
Route::post('/ai/plan', [AiPlanController::class, 'generate']);
Route::get('/training-feedback-v2/{workoutId}', [TrainingFeedbackV2Controller::class, 'getFeedback']);
Route::post('/training-feedback-v2/{workoutId}/generate', [TrainingFeedbackV2Controller::class, 'generate']);
Route::get('/training-feedback-v2/signals/{workoutId}', [TrainingFeedbackV2Controller::class, 'getSignals']);
Route::post('/training-feedback-v2/{id}/question', [TrainingFeedbackV2Controller::class, 'answerQuestion']);
Route::post('/training-feedback-v2/ai/answer', [TrainingFeedbackV2Controller::class, 'answerViaAi']);

Route::get('/workouts', [WorkoutsController::class, 'index']);
Route::post('/workouts', [WorkoutsController::class, 'create']);
Route::get('/workouts/analytics', [WorkoutsController::class, 'analytics']);
Route::get('/workouts/analytics/rows', [WorkoutsController::class, 'analyticsRows']);
Route::get('/workouts/analytics/summary', [WorkoutsController::class, 'analyticsSummary']);
Route::get('/workouts/analytics/summary-v2', [WorkoutsController::class, 'analyticsSummaryV2']);
Route::post('/workouts/upload', [WorkoutsController::class, 'upload']);
Route::post('/workouts/import', [WorkoutsController::class, 'import']);
Route::get('/workouts/{id}', [WorkoutsController::class, 'show']);
Route::delete('/workouts/{id}', [WorkoutsController::class, 'destroy']);
Route::patch('/workouts/{id}/meta', [WorkoutsController::class, 'updateMeta']);
Route::get('/workouts/{id}/signals', [WorkoutsController::class, 'signals']);
Route::get('/workouts/{id}/compliance', [WorkoutsController::class, 'compliance']);
Route::get('/workouts/{id}/compliance-v2', [WorkoutsController::class, 'complianceV2']);
Route::get('/workouts/{id}/alerts-v1', [WorkoutsController::class, 'alertsV1']);

